name = "PrimeSieve"
uuid = ""
authors = ["Tomás Oliveira e Silva <www.johnlapeyre.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Pkg"]
